from ciphers.vigenere import Vigenere
from utility.banburismus import banburismus


def test_banburismus():
    """Test the Banburismus test with two different vigenere
    ciphertext first and then with two equals.
    """
    text1 = ("Once upon a midnight dreary, while I pondered, weak and weary "
             "Over many a quaint and curious volume of forgotten lores.")
    text2 = ("While I nodded, nearly napping, suddenly there came a tapping "
             "As of some one gently rapping, rapping at my chamber door")
    vigenere1 = Vigenere(key_length=8)
    vigenere2 = Vigenere(key_length=8)

    # H1 case
    print("\nGenerated by the same cipher:")
    ciphertext1 = vigenere1.encrypt(text1)
    ciphertext2 = vigenere1.encrypt(text2)
    banburismus(ciphertext1, ciphertext2)

    # H0 case
    print("\nGenerated by the different ciphers:")
    ciphertext1 = vigenere1.encrypt(text1)
    ciphertext2 = vigenere2.encrypt(text2)
    banburismus(ciphertext1, ciphertext2)


if __name__ == "__main__":
    test_banburismus()
